[package]
edition = "2021"
name = "rtc-node"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
livekit-ffi = { path = "./rust-sdks/livekit-ffi" }
neon = { version = "1", features = ["napi-8"] }
prost = "0.12"
prost-types = "0.12"

[profile.release]
lto = true
